package com.phexum.wf.domain.permission;

public enum Permission {
  ALLOWED_FLOOR_0, ALLOWED_FLOOR_1, ALLOWED_FLOOR_2, ALLOWED_FLOOR_3, ALLOWED_FLOOR4, ALLOWED_FLOOR_5, ALLOWED_APARTMENT_1, ALLOWED_APARTMENT_2, ALLOWED_APARTMENT_3, ALLOWED_APARTMENT_4, ALLOWED_APARTMENT_5, ALLOWED_APARTMENT_6, ALLOWED_APARTMENT_7, ALLOWED_APARTMENT_8, ALLOWED_APARTMENT_9, ALLOWED_APARTMENT_10, ALLOWED_APARTMENT_11, ALLOWED_APARTMENT_12, ALLOWED_APARTMENT_13, ALLOWED_APARTMENT_14, ALLOWED_APARTMENT_15, ALLOWED_APARTMENT_16, ALLOWED_APARTMENT_17, ALLOWED_APARTMENT_18, ALLOWED_APARTMENT_19, ALLOWED_APARTMENT_20;
}
